---
- name: Install Web App
  hosts: n1
  become: yes
  tasks: 
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone code from GitHub
      git:
        repo: https://github.com/CeeyIT-Solution/ansible-work-5.git
        dest: /var/www/html
        version: main   # Ensure it pulls from the main branch

    - name: Restart Apache to apply changes
      service:
        name: httpd
        state: restarted
        enabled: yes
...
