---
- name: Under maintenance
  hosts: n1
  become: yes
  tasks: 
    - name: update maintenance page
      copy:
        scr: maintence.html
        dest: /var/www/html/index.html
    - name: Clone code from GitHub
      git:
        repo: https://github.com/CeeyIT-Solutions/food3.git
        dest: /var/www/html

...
