---
- name: Install HTTP server
  hosts: g1
  become: yes
  tasks:
    # Debian and Ubuntu tasks
    - name: Update package list (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Install Apache (Ubuntu/Debian)
      apt:
        name: apache2
        state: present
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Start and enable Apache service (Ubuntu/Debian)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
