---
- name: Install HTTP server
  hosts: g1
  become: yes
  tasks:
    # Amazon Linux tasks
    - name: Install httpd (Amazon Linux)
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start and enable httpd service (Amazon Linux)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon"

    # Ubuntu tasks
    - name: Update package list (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache (Ubuntu)
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Apache service (Ubuntu)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
