---
- name: Install Apache on Ubuntu
  hosts: n1
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
...
