---
- name: Update static page
  copy:
    src: static.html
    dest: /var/www/html/static.html
  notify: Restart Apache

- name: Update Dynamic page
  template:
    src: dynamic.j2
    dest: /var/www/html/dynamic.html
  notify: Restart Apache
